# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
#  theme_default: light
  mode: system
  color: sky

# SEO
marketing:
  seo:
    site_type: PersonalWebsite
    local_business_type: ''
    org_name: 'Institute for Climate and Sustainable Growth, The University of Chicago'
    description: 'Yu Wang (王禹) — postdoctoral scholar in glaciology at the Climate Systems Engineering initiative (CSEi), The University of Chicago. Research: Antarctic ice dynamics, subglacial hydrology, ice–ocean interactions, glacial climate intervention, sea-level rise.'
    twitter: ''
  analytics:
    google_analytics: 'G-TRPE0YG2GQ'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Yu Wang"

# Site footer
footer:
  copyright:
    notice: '© {year} Yu Wang. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false

custom_css:
  - css/white-text.css

feedback:
  tools_form_endpoint: 'https://usebasin.com/f/53e802e0991e'
  fallback_email: 'wangyu@uchicago.edu'
